# Generated by Django 3.2.3 on 2021-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_directmessage_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='lastmsgtimestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
