# Generated by Django 3.2.3 on 2021-05-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_allchats_allchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchat',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup'),
        ),
        migrations.AlterField(
            model_name='allchat',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.directmessage'),
        ),
    ]
