# Generated by Django 3.2.3 on 2021-05-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210525_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchat',
            name='lastmsgtimestamp',
            field=models.DateTimeField(verbose_name='Last Message Timestamp'),
        ),
    ]
