# Generated by Django 3.2.3 on 2021-05-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_allchat_lastmsgtimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allchat',
            old_name='lastmsgtimestamp',
            new_name='timestamp',
        ),
    ]
